version: "3.8"

services:
  woodpecker-server:
    image: woodpeckerci/woodpecker-server:v3.14.0
    container_name: woodpecker-server
    restart: always
    ports:
      - "8000:8000"
    environment:
      - WOODPECKER_HOST=http://woodpecker.sandra.run
      - WOODPECKER_OPEN=true
      - WOODPECKER_ADMIN=SandraHtlr1806 # Dein exakter GitHub-Name
      - WOODPECKER_AGENT_SECRET=supersecret_wechsel_mich

      - WOODPECKER_GITHUB=true
      - WOODPECKER_GITHUB_CLIENT=Ov23liHJYvEg1YTICra3
      - WOODPECKER_GITHUB_SECRET=344e70bd617c661107cc4675458b4965c0751484
      - WOODPECKER_SKIP_WEBHOOK_CREATION=true
      - WOODPECKER_DATABASE_DATASOURCE=/var/lib/woodpecker/woodpecker.sqlite
    volumes:
      - woodpecker-data:/var/lib/woodpecker

  woodpecker-agent:
    image: woodpeckerci/woodpecker-agent:v3.14.0
    container_name: woodpecker-agent
    restart: always
    depends_on:
      - woodpecker-server
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      - WOODPECKER_SERVER=woodpecker-server:9000
      - WOODPECKER_AGENT_SECRET=supersecret_wechsel_mich
      - WOODPECKER_BACKEND=docker
      - WOODPECKER_DOCKER_DNS=8.8.8.8,1.1.1.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  woodpecker-data: